name: my_design
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  get: ^4.6.5

  flutter_screenutil: ^5.6.0

  dio: ^4.0.6

  get_storage: ^2.0.3

  shared_preferences: ^2.0.15

  device_info_plus: ^8.0.0

  screenshot: 1.2.3

  permission_handler: ^10.2.0

  image_gallery_saver: ^1.7.1

  image_picker: ^0.8.4+8

  image_cropper: ^3.0.1

  google_fonts: ^3.0.1

  screen_recorder: 0.0.3

  audioplayers: ^1.1.1

  conditional_builder_null_safety: ^0.0.6

  flutter_colorpicker: ^1.0.3

  #share
  share_plus: ^6.3.0
  path_provider: ^2.0.11


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

  flutter_lints: ^2.0.0
flutter_icons:

  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon_app.png"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/logo.jpg
     - assets/images/
     - assets/audio/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: high-summit
      fonts:
        - asset: assets/font/High-Summit.ttf

    - family: Open_Sans
      fonts:
        - asset: assets/font/OpenSans-Regular.ttf

    - family: Playfair_Display
      fonts:
        - asset: assets/font/PlayfairDisplay-Regular.ttf

    - family: NotoSansArabic-Regular
      fonts:
        - asset: assets/font/NotoSansArabic-Regular.ttf

    - family: alfont_Regular
      fonts:
        - asset: assets/font/alfont_Regular.otf

    - family: Cairo-Regular
      fonts:
        - asset: assets/font/Cairo-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
